import * as path from 'path';
import Grammar from './grammar';

const kind = new Grammar('Kind', {
  path: path.join(__dirname, '..', 'tree-sitter-kind'),
  terms: {
    'f60_literal': 'number',
    'u60_literal': 'number',
    'u120_literal': 'number',
    'n_literal': 'number',
    'string': 'string',
    'char': 'string',
    // operators
    '"="': 'operator',
    '"+="': 'operator',
    '"-="': 'operator',
    '"*="': 'operator',
    '"/="': 'operator',
    '"%="': 'operator',
    '"<<="': 'operator',
    '">>="': 'operator',
    '">>>="': 'operator',
    '"&="': 'operator',
    '"^="': 'operator',
    '"|="': 'operator',
    '"!"': 'operator',
    '"+"': 'operator',
    '"-"': 'operator',
    '"*"': 'operator',
    '"/"': 'operator',
    '"%"': 'operator',
    '"=="': 'operator',
    '"==="': 'operator',
    '"!="': 'operator',
    '"!=="': 'operator',
    '">="': 'operator',
    '"<="': 'operator',
    '"=>"': 'operator',
    '">"': 'operator',
    '"<"': 'operator',
    '":"': 'operator',
    '"?"': 'operator',
    '"&&"': 'operator',
    '"||"': 'operator',
    '"&"': 'operator',
    '"~"': 'operator',
    '"^"': 'operator',
    '">>"': 'operator',
    '">>>"': 'operator',
    '"<<"': 'operator',
    '"|"': 'operator',
    '"++"': 'operator',
    '"--"': 'operator',
    '".."': 'operator',
    '"@"': 'operator',
    '"::"': 'operator',
    '"$"': 'operator',
    // comments
    'line_comment': 'comment',
    'doc_string': 'comment',
    'hash_bang_line': 'comment',
    // keywords
    '"record"': 'keyword',
    '"type"': 'keyword',
    '"if"': 'keyword',
    '"let"': 'keyword',
    '"else"': 'keyword',
    '"match"': 'keyword',
    '"with"': 'keyword',
    '"into"': 'keyword',
    '"in"': 'keyword',
    '"do"': 'keyword',
    '"ask"': 'keyword',
    '"open"': 'keyword',
    '"specialize"': 'keyword',
    '"return"': 'keyword',
    // punctuation
    '"("': 'punctuation',
    '")"': 'punctuation',
    '"{"': 'punctuation',
    '"}"': 'punctuation',
    '";"': 'punctuation',
    '"["': 'punctuation',
    '"]"': 'punctuation',
    '"."': 'punctuation',
    '","': 'punctuation',
  },
  complex: [
    'identifier',
    'upper_id',
    'lower_id',
    'constructor_identifier',
    'field_signature',
    'member_signature',
    'rename_pattern',
    'local_name',
    'implicit_parameter',
    'explicit_parameter',
    'lam_parameter',
    'match_pattern',
    'dot_access',
    'constructor_match_pattern',
  ],
  scopes: {
    'constructor_identifier > lower_id': 'method',

    'field_signature > identifier': 'property',
    'field_signature > constructor_identifier': 'property',

    'implicit_parameter > identifier': 'type-parameter',
    'implicit_parameter > constructor_identifier': 'type-parameter',

    'lam_parameter > identifier': 'parameter',
    'lam_parameter > constructor_identifier': 'parameter',

    'explicit_parameter > identifier': 'parameter',
    'explicit_parameter > constructor_identifier': 'parameter',

    'member_signature > identifier': 'enum-member',
    'member_signature > constructor_identifier': 'enum-member',

    'constructor_match_pattern > constructor_identifier > dot_access > lower_id':
      'enum-member',

    'constructor_match_pattern > identifier > lower_id': 'enum-member',

    'rename_pattern > identifier': 'property',

    'identifier': 'variable',
    'upper_id': 'function',
  },
});

export default kind;
